server {
    listen 443 ssl;
    server_name svt-olog01.clsi.ca;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    ssl_certificate /cert.pem;
    ssl_certificate_key /privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
